### ISSUE TITLE
Discussion about how X3D modes and sources can be applied to the IFC schema

### ISSUE THREAD

**Issue by Moult** [castle-engine/demo-models#9]
Hi there!

I've been developing various foss libraries and applications to do with something known as "IFC". IFC is a data schema for describing buildings used by architects, engineers, and the construction industry.

IFC heavily leans on the X3D specification to support textures (specifically multi textures), and borrows concepts such as modes and sources. I came across your test files and commentary including proposals: https://castle-engine.io/x3d_multi_texturing.php - would you be available for a casual chat (say an hour?) to discuss some of my understanding of your commentary and how this can translates to the IFC spec (including your proposed fixes) and how this maps to more modern material definitions (e.g. PBR workflows in modern rendering engines like Blender's Cycles).

Cheers :) Great website and love the work you're doing by the way!

**Comment by michaliskambi** [comment]
Hi! Thank you for the good words. Yes, I'm happy to meet and talk :) We can do it this week. Let me move this conversation to private email then, I see your mail on https://github.com/Moult -- I'll send you an email in 5 minutes from `michalis.kambi AT protonmail.com` and let's schedule a talk.
